language: cpp
script: cmake

matrix:
    include:
        # OSX
        - env: PYTHON=python
          os: osx
        # Linux
        - env: PYTHON=python
          os: linux
          python: '2.7'
          addons:
            apt:
              packages:
                - util-linux
                - cmake
        - env: PYTHON=python3.4
          os: linux
          python: '3.4'
          addons:
            apt:
              packages:
                - util-linux
                - cmake

script:
    - which cmake
    - cmake --version
    - which $PYTHON
    - $PYTHON --version
    - export PATH="/Users/travis/Library/Python/2.7/bin:$PATH"
    - $PYTHON setup.py install --user && $PYTHON ./test/test.py
