language: cpp
script: cmake

matrix:
    include:
        # OSX
        - os: osx
        # Linux
        - os: linux
          addons:
            apt:
              packages:
                - util-linux
                - python
                - cmake

script:
    - cmake --version
    - python --version
    - PWD=`pwd`
    - mkdir usr
    - PREFIX="$PWD/usr"
    - export PATH="$PREFIX/bin:$PATH"
    - export PYTHONPATH="$PREFIX"
    - python setup.py install --prefix $PREFIX && python ./test/test.py
