language: cpp
script: cmake

matrix:
    include:
        # OSX
        - os: osx
        # Linux
        - os: linux
          addons:
            apt:
              packages:
                - util-linux
                - python

script:
    - python setup.py install --user && python ./test/test.py
