script: cmake
language: python

matrix:
    include:
        # OSX
        - env:
            - TOXENV=py27
          os: osx
          language: generic
          python: '2.7'
        # Linux
        - env: 
            # - PYTHONPATH=/home/travis/.local/lib/python2.7/site-packages/
            - TOXENV=py27
          os: linux
          python: '2.7'
          addons:
            apt:
              packages:
                - util-linux
                - cmake 
        - env: 
            # - PYTHONPATH=/home/travis/.local/lib/python3.4/site-packages/
            - TOXENV=py34
          os: linux
          python: '3.4'
          addons:
            apt:
              packages:
                - util-linux
                - cmake
        - env: 
            # - PYTHONPATH=/home/travis/.local/lib/python3.5/site-packages/
            - TOXENV=py35
          os: linux
          python: '3.5'
          addons:
            apt:
              packages:
                - util-linux
                - cmake
install:
    - which cmake
    - cmake --version
    - which python
    - python --version
    - export DEBUG=1
    - export PATH="/Users/travis/Library/Python/2.7/bin:$PATH"
    - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then pip install tox; fi
    - if [[ "${TRAVIS_OS_NAME}" != "linux" ]]; then pip install --user tox; fi
script:
    - tox
