language: cpp
script: cmake

matrix:
    include:
        # OSX
        - os: osx
        # Linux
        - os: linux
          addons:
            apt:
              packages:
                - util-linux
                - python
                - cmake

script:
    - cmake --version
    - python --version
    - export PATH="/Users/travis/Library/Python/2.7/bin:$PATH"
    - python setup.py install --user && python ./test/test.py
