script: cmake
language: python

matrix:
    include:
        # OSX
        - os: osx
          python: '2.7'
        # Linux
        - env: PYTHONPATH=/home/travis/.local/lib/python2.7/site-packages/
          os: linux
          python: '2.7'
          addons:
            apt:
              packages:
                - util-linux
                - cmake 
        - env: PYTHONPATH=/home/travis/.local/lib/python3.4/site-packages/
          os: linux
          python: '3.4'
          addons:
            apt:
              packages:
                - util-linux
                - cmake

script:
    - which cmake
    - cmake --version
    - which python
    - python --version
    - export PATH="/Users/travis/Library/Python/2.7/bin:$PATH"
    - python setup.py install --user && python ./test/test.py
