environment:
  matrix:
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"

# install:
#   # Install pkg-config from chocolatey
#   - cinst pkgconfiglite

build_script:
  - cmd: "set PATH=%PYTHON%\\Scripts;%PATH%"
  - cmd: "%PYTHON%\\python.exe -m pip install wheel" # pykg-config
  - cmd: "%PYTHON%\\python.exe setup.py install"
  - cmd: "%PYTHON%\\python.exe test\\test.py"
